# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 14:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField(default=0)),
                ('blood_pressure', models.CharField(default=None, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_choice', models.CharField(choices=[('mine', 'My Doctor'), ('other', 'Other Doctor')], default=None, max_length=10)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(blank=True, default=None)),
                ('reason', models.TextField(default=None, max_length=500)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClerkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default=None, max_length=60)),
                ('number', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalized', models.BooleanField(default=False)),
                ('street', models.TextField(default=None, max_length=250)),
                ('city', models.CharField(default=None, max_length=40)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default=None, max_length=15)),
                ('zip_code', models.IntegerField(default=None)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], default=None, max_length=20)),
                ('blood_type', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default=None, max_length=3)),
                ('ethnicity', models.CharField(choices=[('white', 'White'), ('african_american', 'Black or African American'), ('hispanic', 'Hispanic or Latino'), ('native', 'American Indian or Alaska Native'), ('islander', 'Native Hawaiian or Other Pacific Islander'), ('other', 'Other')], default=None, max_length=20)),
                ('special_needs', models.TextField(default=None, max_length=50)),
                ('organ_donor', models.BooleanField(default=False)),
                ('height', models.CharField(default=None, help_text='Example: 5ft 10in', max_length=12)),
                ('weight', models.CharField(default=None, help_text='Example: 120 lb', max_length=7)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='HealthNetApp.DoctorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(default=None, max_length=30)),
                ('drug_id', models.PositiveIntegerField(default=0)),
                ('directions', models.TextField(default=None, max_length=250)),
                ('expiration', models.DurationField(default=datetime.timedelta)),
                ('status', models.BooleanField(default=None)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='HealthNetApp.PatientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0, null=True)),
                ('phone', models.CharField(help_text='e.g +1(585)123-4567', max_length=15, null=True)),
                ('middle_name', models.CharField(default=None, max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'I choose to not specify')], default='other', max_length=10)),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('clerk', 'Clerk')], default='patient', max_length=10)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='HealthNetApp.PatientProfile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='clerkprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='appointmenttoken',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apt_token', to='HealthNetApp.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='appointmenttoken',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apt_token', to='HealthNetApp.PatientProfile'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='HealthNetApp.AppointmentToken'),
        ),
    ]
