# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None)),
                ('msg', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointmenttoken',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='number',
            field=models.IntegerField(default=None, max_length=20),
        ),
    ]
