# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 14:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthNetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField(default=0)),
                ('blood_pressure', models.CharField(default=None, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 10, 18, 10, 26, 26, 476310))),
                ('reason', models.TextField(default=None, max_length=500)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClerkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalized', models.BooleanField(default=False)),
                ('street', models.TextField(default=None, max_length=250)),
                ('city', models.CharField(default=None, max_length=40)),
                ('state', models.CharField(default=None, max_length=2)),
                ('zip_code', models.IntegerField(default=None, max_length=10)),
                ('civil_status', models.CharField(default=None, max_length=20)),
                ('blood_type', models.CharField(default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(default=None, max_length=30)),
                ('drug_id', models.PositiveIntegerField(default=0)),
                ('directions', models.TextField(default=None, max_length=250)),
                ('expiration', models.DurationField(default=datetime.timedelta)),
                ('status', models.BooleanField(default=None)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='HealthNetApp.PatientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(help_text='e.g +1(585)123-4567', max_length=15, null=True)),
                ('middle_name', models.CharField(default=None, max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'I choose to not specify')], default='Other', max_length=10)),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor')], default='Patient', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='defaultuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='DefaultUser',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='clerkprofile',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_profile', to='HealthNetApp.UserProfile'),
        ),
        migrations.AddField(
            model_name='appointmenttoken',
            name='clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apt_token', to='HealthNetApp.ClerkProfile'),
        ),
        migrations.AddField(
            model_name='appointmenttoken',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apt_token', to='HealthNetApp.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='appointmenttoken',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apt_token', to='HealthNetApp.PatientProfile'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='HealthNetApp.AppointmentToken'),
        ),
    ]
