# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 13:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNetApp', '0002_auto_20161018_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttoken',
            name='doctor_choice',
            field=models.CharField(choices=[('mine', 'My Doctor'), ('other', 'Other Doctor')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='HealthNetApp.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='appointmenttoken',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 25, 9, 59, 45, 33985)),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='zip_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'I choose to not specify')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('clerk', 'Clerk')], default='patient', max_length=10),
        ),
    ]
