# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNetApp', '0002_auto_20161107_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
